#!/usr/bin/env python

# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: MIT

"""Consume a text file containing a list of SystemVerilog sources
and write the source list to stdout in package dependence order."""

import os
import sys

from platlib import sort_sv_packages


def load_sv_files(fname):
    """Return the contents of a file as a list, one entry per line.
    Ignore any line beginning with #."""

    sv_list = []

    if fname:
        f = open(fname, 'r')
    else:
        f = sys.stdin

    for line in f:
        line = line.strip()
        if line and line[0] != '#':
            sv_list.append(line)

    return sv_list


def main():
    if len(sys.argv) > 2:
        sys.stderr.write('Usage: sort_sv_pkgs [<file>]\n\n')
        sys.stderr.write('Sort a collection of SystemVerilog '
                         'packages in dependence order.\n')
        sys.stderr.write('If file is not specified, read from stdin.\n')
        sys.exit(1)

    # Load the input file into a list
    pkg_list = load_sv_files(sys.argv[1] if (len(sys.argv) == 2) else None)
    # Sort the file list in dependence order
    sorted_pkg_list = sort_sv_packages.sort_pkg_list(pkg_list)

    for p in sorted_pkg_list:
        print(p)


if __name__ == "__main__":
    main()
